language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t esanjoyganguly/docker-react -f Dockerfile.dev .

script:
  - docker run esanjoyganguly/docker-react npm run test -- --coverage
 
