language: generic
sudo: required
install: travis_wait 30 npm install

services:
  - docker

before_install:
  - docker build -t esanjoyganguly/docker-react -f Dockerfile.dev .

script:
  - docker run esanjoyganguly/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-node"
  env: "DockerReactNode-env"
  bucket_name: "elasticbeanstalk-eu-west-1-376482541310"
  bucket_path: "docker-react-node"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
